### ISSUE TITLE
Add footer to docs

### ISSUE THREAD

**Issue by DrKillshot** [DrKillshot/unwrap#27]
[https://vitepress.dev/reference/default-theme-footer](https://vitepress.dev/reference/default-theme-footer)

**Comment by SufyaanKhateeb** [comment]
I can take this up. Do you have any reference in mind for the design?

**Comment by DrKillshot** [comment]
Not really, something simple would be fine 

<img width="1581" alt="Screenshot 2024-10-23 at 22 41 58" src="https://github.com/user-attachments/assets/9964a97c-b066-4b6c-89e0-dac3c6ec15ee">

Vitepress should have this out of the box
